jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # السماح للـ GitHub Actions بالكتابة في الريبو
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: MohamedARoshdy
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit & Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
