name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # تشغيل كل يوم في منتصف الليل
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: MohamedARoshdy
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/snake.svg
          git add output/snake.svg
          git commit -m "Update snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
